### PR TITLE
enabling config_dm_crypt

### PR DESCRIPTION
**Pull request by georghildebrand**
### dm_crypt support in kernel

I hope this fixes the missing dm_crypt support. have not tried the build myself as i am newbe in this topic. Hope it works

### CODE REVIEW

**Comment by georghildebrand** [comment]
@ayufan please tell me what you think.

**Comment by ayufan** [comment]
OK, but dm-crypt is present as kernel module, why you want to enable that in `vmlinux`?

**Comment by georghildebrand** [comment]
Ah, I thought that's the conf for Rock chip

>

**Comment by georghildebrand** [comment]
@ayufan, sorry to be not very clear. i donwloaded a latest build for rockspi 4 and the module was missing. as i understood the folder structure this should enable the module in the next build ... however, i am not super accumen here

**Pull request closed without merging**
