### PR TITLE
Nuumio 4.4 pcie scan sleep

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ayufan** [comment]
This no longer seems related @nuumio  :)

**Comment by ghost** [comment]
Right, I forgot I got this one open. Actually this might be related as 1163 crashes with my LSI controller. After rebasing these changes on top of 1163 my tests look promising. I just need to make few little modifications to commits. I'll let you know how it goes.

**Comment by ghost** [comment]
I've been running this for couple of days now and haven't seen any problems or side effects. I've successfully run clean kernel build on my test RP64 a few times (like 10-15 times or so) and otherwise it's just been idling and off during night time. WiFi/BT module has been connected, but no WiFi network nor BT devices configured. This has all been done on Bionic minimal build. I also did a quick test with Pine NVMe adapter and 970 Evo plus and they still work.

I haven't seen anybody else commenting on IRC/Discord or in Rockchip ticket related to this (https://github.com/rockchip-linux/kernel/issues/116). It's quite possible nobody has tried my build (https://github.com/nuumio/linux-kernel/releases/tag/nuumio-4.4-pcie-scan-sleep-02).

From my point of view this can be merged if you want. Then we should at least see if it breaks someone else's system :)

**Comment by ayufan** [comment]
I think that this is great idea to try it. Thanks!

**Comment by rich0** [comment]
I just tried this kernel and as far as I can tell it is ignoring the command line parameter.  Some dmesg excerpts:

dmesg | grep pcie
[    0.000000] Linux version 4.4.167-nuumio-4.4-pcie-scan-sleep-02 (rock64@guineapig) (gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) ) #1 SMP Tue Apr 2 22:29:50 EEST 2019
[    0.000000] Kernel command line: earlycon=uart8250,mmio32,0xff1a0000 swiotlb=1 rw panic=10 init=/sbin/init coherent_pool=1M ethaddr=da:58:af:c9:1b:23 eth1addr= serial=d32f51a9fd69c5e cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 root=LABEL=linux-root rootwait rootfstype=ext4 pcie_rk_bus_scan_delay=5000
[    1.461631] of_get_named_gpiod_flags: parsed 'gpio' property of node '/vcc3v3-pcie-regulator[0]' - status (0)
[    1.461679] reg-fixed-voltage vcc3v3-pcie-regulator: Looking up vin-supply from device tree
[    1.461723] vcc3v3_pcie: supplied by dc_12v
[    1.461776] vcc3v3_pcie: 3300 mV
[    1.461945] reg-fixed-voltage vcc3v3-pcie-regulator: vcc3v3_pcie supplying 3300000uV
[    2.020344] usb usb1: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 ehci_hcd
[    2.087863] usb usb2: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 ohci_hcd
[    2.178216] dwmmc_rockchip fe310000.dwmmc: deferring for a max of 2000ms while pcie port initializes. Waited 0ms so far.
[    2.951721] usb usb3: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 xhci-hcd
[    2.961009] usb usb4: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 xhci-hcd
[    3.009995] usb usb3: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 xhci-hcd
[    3.096073] usb usb4: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 xhci-hcd
[    3.185958] usb usb5: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 ehci_hcd
[    3.353344] usb usb6: Manufacturer: Linux 4.4.167-nuumio-4.4-pcie-scan-sleep-02 ohci_hcd
[    3.408102] dwmmc_rockchip fe310000.dwmmc: deferring for a max of 2000ms while pcie port initializes. Waited 1230ms so far.
[    3.760042] dwmmc_rockchip fe310000.dwmmc: deferring for a max of 2000ms while pcie port initializes. Waited 1582ms so far.
[    3.806605] vcc3v3_pcie: disabling
[    3.829136] dwmmc_rockchip fe310000.dwmmc: deferring for a max of 2000ms while pcie port initializes. Waited 1651ms so far.
[    4.179744] phy phy-pcie-phy.9: Looking up phy-supply from device tree
[    4.179748] phy phy-pcie-phy.9: Looking up phy-supply property in node /pcie-phy failed
[    4.187398] rockchip-pcie f8000000.pcie: GPIO lookup for consumer ep
[    4.187417] rockchip-pcie f8000000.pcie: using device tree for GPIO lookup
[    4.187481] of_get_named_gpiod_flags: parsed 'ep-gpios' property of node '/pcie@f8000000[0]' - status (0)
[    4.187822] rockchip-pcie f8000000.pcie: Looking up vpcie3v3-supply from device tree
[    4.188023] rockchip-pcie f8000000.pcie: Looking up vpcie1v8-supply from device tree
[    4.188037] rockchip-pcie f8000000.pcie: Looking up vpcie1v8-supply property in node /pcie@f8000000 failed
[    4.188078] rockchip-pcie f8000000.pcie: no vpcie1v8 regulator found
[    4.198391] rockchip-pcie f8000000.pcie: Looking up vpcie0v9-supply from device tree
[    4.198426] rockchip-pcie f8000000.pcie: Looking up vpcie0v9-supply property in node /pcie@f8000000 failed
[    4.198474] rockchip-pcie f8000000.pcie: no vpcie0v9 regulator found
[    4.207104] rockchip-pcie f8000000.pcie: bus-scan-delay-ms in device tree is 1000 ms
[    4.223984] rockchip-pcie f8000000.pcie: missing "memory-region" property
[    4.232170] PCI host bridge /pcie@f8000000 ranges:
[    4.254096] rockchip-pcie f8000000.pcie: invalid power supply
[    4.760956] rockchip-pcie f8000000.pcie: PCIe link training gen1 timeout!
[    4.772949] rockchip-pcie f8000000.pcie: deferred probe failed
[    4.785180] rockchip-pcie: probe of f8000000.pcie failed with error -110
[    4.798788] dwmmc_rockchip fe310000.dwmmc: detected pcie initialized, continuing...

As you can see there is no sign of the message indicating that the delay is being implemented, and there is still a gen1 timeout.

**Comment by ghost** [comment]
My scan bus sleep patch only takes effect **after** pcie link training completes. Didn't remember you had that timeout problem in link training. I had a crash after that in bus scan.

Seems you got same crash than I did by using a mining adapter (in rockchip ticket). Did you try with that?

**Comment by rich0** [comment]
For the record, if I use a 1x mining adapter the LSI card now works:
lspci:
01:00.0 Serial Attached SCSI controller: LSI Logic / Symbios Logic SAS2116 PCI-Express Fusion-MPT SAS-2 [Meteor] (rev 02)

So, something is still preventing training without the 1x adapter (this is an 8x card in the 4x slot).  Happy to continue to test solutions to that, otherwise I'll go ahead and see how well the card actually works...

**Comment by RchGrav** [comment]
I believe that the riser is shorting PCIe pin A1 to B17 to provide presence as a 1x card.. See https://imgur.com/a/AJB71Ih  That being said.. shorting pin A1 to the second presence pin B31 should make it detect as a 4x card.   (I don't have a RockPro64 to test this.)

**Pull request merged**
