### PR TITLE
Added IPVS kernel ipv6 support, protocols and balancing strategies

### PR DESCRIPTION
**Pull request by chminngi**
@ayufan  
I added a PR with commit tag (1d8d429 ) for some additional kernel modules for 
IPVS needed for docker swarm. 
Can you look at this PR and add it to rock64 and rockpro64 for 0.6 and 0.7? 
Thank you

Added IPV6 support
Added protocol support (TCP,  UDP, AH, ESP, SCTP)
Added balancing support (WRR, WLC, LC, FO, OVF, LBLC, LBLCR, DH, SH, SED, NQ)

### CODE REVIEW

**Comment by giminni** [comment]
wrong set

**Comment by ayufan** [comment]
Can you rebase these changes?

**Comment by ayufan** [comment]
This is done.

**Comment by sputnik13** [comment]
@ayufan uh, what does "This is done" mean?  The PR was closed rather than merged, and I don't see the IP VS configs in the kernel configs in master.  The IPVS options are necessary for running kubernetes with IPVS networking enabled.  Would be very useful to have in default build.

**Comment by samirpatelgx** [comment]
Yeah, it doesn't look like the most recent updates to the builds have IPVS support. I am still getting the following error message when I try to join a node into Kubernetes:

`[WARNING RequiredIPVSKernelModulesAvailable]: the IPVS proxier will not be used, because the following required kernel modules are not loaded: [ip_vs_rr ip_vs_wrr ip_vs_sh ip_vs] or no builtin kernel ipvs support: map[ip_vs:{} ip_vs_rr:{} ip_vs_wrr:{} ip_vs_sh:{} nf_conntrack_ipv4:{}]`

This doesn't happen with my Raspbian Lite distro's. It's only an issue with this Debian Distro.

Only real solution currently is to go with iptables unless this is resolved. This is an issue because this workaround has several disadvantages.

**Comment by jmreicha** [comment]
IPVS support was just released in v0.7.10 (in a different PR).  I just checked and have the modules after flashing to the new image.

```
...
ip_vs_sh               16384  0
ip_vs_wrr              16384  0
ip_vs_rr               16384  0
ip_vs                 147456  6 ip_vs_rr,ip_vs_sh,ip_vs_wrr
nf_conntrack_ipv4      24576  16
...
```

**Comment by sputnik13** [comment]
@jmreicha thanks, I see 0.7.10 mentions rebased kernel, I guess I'll have to wait for 0.7.10 release (it's pre-release now) and update.

**Comment by samirpatelgx** [comment]
@jmreicha I already updated it temporarily through modprobe and /etc/module but thanks for the update on that. Warnings have gone away now when I join a node but now I'm facing another issue. All nodes are set to ready status but one of the pods on my Rock64 node is giving me an error.

kubectl get pods --all-namespaces -o wide
`
NAMESPACE     NAME                             READY     STATUS             RESTARTS   AGE       IP              NODE      NOMINATED NODE
kube-system   coredns-78fcdf6894-9wrrg         1/1       Running            0          3h        10.244.0.7      master    <none>
kube-system   coredns-78fcdf6894-rl7d5         1/1       Running            0          3h        10.244.0.6      master    <none>
kube-system   etcd-master                      1/1       Running            0          3h        192.168.1.200   master    <none>
kube-system   kube-apiserver-master            1/1       Running            0          3h        192.168.1.200   master    <none>
kube-system   kube-controller-manager-master   1/1       Running            0          3h        192.168.1.200   master    <none>
kube-system   kube-flannel-ds-arm-h2nk7        1/1       Running            0          3h        192.168.1.200   master    <none>
kube-system   kube-flannel-ds-arm64-ccdm6      0/1       CrashLoopBackOff   36         3h        192.168.1.253   worker3   <none>
kube-system   kube-proxy-f2zg7                 1/1       Running            0          3h        192.168.1.200   master    <none>
kube-system   kube-scheduler-master            1/1       Running            0          3h        192.168.1.200   master    <none>
`

kubectl logs kube-flannel-ds-arm64-ccdm6 --namespace kube-system
`
I1009 01:14:53.630552       1 main.go:475] Determining IP address of default interface
I1009 01:14:53.633310       1 main.go:488] Using interface with name eth0 and address 192.168.1.253
I1009 01:14:53.633512       1 main.go:505] Defaulting external address to interface address (192.168.1.253)
E1009 01:15:23.732120       1 main.go:232] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-arm64-ccdm6': Get https://10.96.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-arm64-ccdm6: dial tcp 10.96.0.1:443: i/o timeout
`

It's only happening on this Rock64. Not sure if it's still an IPVS issue or some kind of firewall issue. Any suggestions on this? Also looks like Flannel is unable to create a Flannel virtual network on my Rock64 like it is created on my RPI.

ip route

`
169.254.0.0/16 dev flannel.1 proto kernel scope link src 169.254.136.147 metric 223
`

This is missing from my Rock64.

**Comment by jmreicha** [comment]
@samirpatelgx I've been struggling to get a cluster up and stable using the new version.  I finally got one up with Flannel but didn't see those errors.  It looks like maybe there's some issue connecting to the apiserver?

**Pull request closed without merging**
